# Numerical Python End to End in Detail


Numpy:

Numpy- is a Numerical Python

It is developed by Travis Oliphant in 2005

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays
Why:

Numpy is built using python, and most of the part which requires fatser execution is developed using c or c++,So it is very fast in execution.

Numpy arrays are called as ndarray

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it stores numpy arrays at one continuous location

Numpy codes are available at: https://github.com/numpy/numpy


# Installation of Numpy

In [1]:
import numpy as np

np.__version__

'1.21.2'

In [2]:
# create a numpy array using list
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
print(type(arr))


lst = [10,20,30,40]

ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [3]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)


# lets check the dimensions of the array

print("Number of dimensions: ",arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimensions:  1


In [4]:
# Create numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))
print("Dimensions: ",ar.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
Dimensions:  1
