#  Different Dimensional arrays:

In [2]:
# 0-D array
import numpy as np

arr = np.array(200)

print(arr) 

# dimensions

print("Dimensions: ",arr.ndim)

200
Dimensions:  0


In [3]:
# 1-D array

arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

# dimesnsions
print(arr.ndim)

# Access elements an 1-D array

print("Element present at 4th index: ",arr[4])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
Element present at 4th index:  5


In [4]:


# 2-D array
# Arrays ahaving 1-D array as input element, are called as 2-D array
ar = [[1,2,3],[4,5,6]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)



[[1 2 3]
 [4 5 6]]
Dimensions:  2


In [5]:
# Access the elements of 2-D array
#one way is to write

print(arr[0])
print(arr[0][2])
# another way is like
print(arr[1])
print(arr[1,1])

# dimensions

print("Dimensions: ",arr.ndim)

[1 2 3]
3
[4 5 6]
5
Dimensions:  2


In [6]:
# 3-D array
# array that has 2-D arrays (matrices) as its elements is 
# called 3-D array.
ar = [[[1, 2, 3], [4, 5, 6]] , [[10, 20, 30], [40, 50, 60]]]
print(type(ar))

arr = np.array(ar)
print(arr)
print(type(arr))
print("Dimensions:",arr.ndim)
# dimensions

print(arr.ndim)

<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
Dimensions: 3
3


In [7]:
# access the elements of the 3-D array
# One way is 

print(arr[1])
print(arr[0][0])
print(arr[0][0][2])

# Another way


print(arr[1])
print(arr[0,0])
print(arr[0,0,2])

[[10 20 30]
 [40 50 60]]
[1 2 3]
3
[[10 20 30]
 [40 50 60]]
[1 2 3]
3


In [8]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5
