In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Slice
print("Length: ",len(arr))
print(arr[0:9])

# [start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
Length:  9
[1 2 3 4 5 6 7 8 9]


In [3]:
print(arr[0:5])

[1 2 3 4 5]


In [5]:
print(arr[4:])

[5 6 7 8 9]


# Negative Indices

In [6]:
print(arr)
print(arr[-1])

print(arr[-9])

[1 2 3 4 5 6 7 8 9]
9
1


In [7]:
print(arr[-3:-7])

[]


In [8]:
# Step value in slicing a Numpy array
print(arr)
print(arr[0:9:2]) 

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


# Slicing of 2_D Array

In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#print(arr)
print("\n")

print(arr[1])
print(arr[1,2])

print(arr[0,1:4 ])

# arr[2_d array loc, range of elements]


#print(arr[0, 1:4]) 



[ 6  7  8  9 10]
8
[2 3 4]


In [10]:
print(arr)
print(arr[0:2,0:3])

#print(arr[0:2, 2]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]


In [11]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15
(3, 5)


In [12]:


# 2, 3
# 20,30

print(arr[0:2,1:3])


# 20 30 40
# 22 33 44

print("\n",arr[1:3,1:4])






[[ 2  3]
 [20 30]]

 [[20 30 40]
 [22 33 44]]
