# Data Types in NumPy

In [2]:
import numpy as np
# dtype
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [3]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype) 

['apple' 'banana' 'cherry']
<U6


In [4]:
# Creating Arrays With a Defined Data Type

arr = np.array([1,2,3,4],dtype='int')

print(arr)
print(arr.dtype)


arr = np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4. 5. 6.]
float64


In [5]:
# int with 4 bytes
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [6]:


# Errors

#arr = np.array(['a', '2', '3'], dtype='i') 
print(arr)
print(arr.dtype)



[1 2 3 4]
int32


Data Type Conversion

In [7]:
# float to int
arr = np.array([1.1,2.2,3.3,4.4])

newarr = arr.astype('int')

#newarr = arr.astype('i')
print(arr)
print(newarr)
print(newarr.dtype) 

[1.1 2.2 3.3 4.4]
[1 2 3 4]
int32


In [9]:
# int to bool

arr = np.array([1,2,5.5,0])

newarr = arr.astype('bool')
print(arr)
print(newarr)
print(newarr.dtype) 

[1.  2.  5.5 0. ]
[ True  True  True False]
bool


Difference Between Copy and View

In [10]:


# Copy: It is goint to create new instance for your values

arr = np.array([1,2,3,4,5,6])
x = arr.copy()
print(x)
x[0] = 100
print(x)


print(arr)
#print(x) 



[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [11]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 200
print(arr)
print(x) 

[200   2   3   4   5]
[200   2   3   4   5]


In [12]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
#print(y.base) 

None



Array Reshaping

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)
newarr = arr.reshape(4, 3)
newarr1 = arr.reshape(12, 1)
newarr2 = arr.reshape(3, 4)

print(newarr) 
print(newarr1)
print(newarr2)


# Create a 2d array and then conveet it into 1-D array

12
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 2, 2)
newarr1 = arr.reshape(2, 3, 2)
newarr2 = arr.reshape(2, 3, 2)


print(newarr)
print(newarr1)
print(newarr2)


# convert 3-D array into 1-D array

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
