# Join array

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 


[1 2 3 4 5 6]


In [2]:
# Array Concatenation using axis option

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,6 ], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)



[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]



Joining Arrays Using Stack Functions :

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.


In [3]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [7]:
# hstack function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [8]:
# stacking along the columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
# stacking along depth
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Array

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
newarr = np.split(arr, 3, axis = 1)
print(newarr)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
# newarr = np.split(arr, 4) # This will raise an Value Error
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [18]:
# IF no_of elements are less then it adjust in last array
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [19]:
# Array splitting on 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4, axis = 0)

for i in newarr:
    print(i,"\n") 
print("\n\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]] 

[[11 12]] 






In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], 
                [13, 14, 15], [16, 17, 18]])
print(arr.shape)
newarr = np.array_split(arr, 3)

print(newarr) 

(6, 3)
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [21]:
# Array splitting on axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr) 
#newarr = np.array_split(arr, 3, axis=0)

#print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# using hsplit() opposite of hstack()

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [23]:
 import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6], dtype=int64),)


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7], dtype=int64),)


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6], dtype=int64),)


In [26]:
## searchsorted()

# performs a binary search in the array, and returns the index 
# where the specified value would be inserted to maintain 
# the search order.


arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x) 

1


In [27]:
## Side

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


In [33]:
### Multiple Values

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4,6])

print(x)

[1 2 3]


Sorting Arrays

In [35]:
#int
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [37]:
#string
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [38]:
#bool
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


In [39]:
#Sort a 2-D array:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


NumPy Filter Array

In [40]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [42]:
#Create a filter array that will return only values higher than 42:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False, False, True, True]
[43 44]
