In [1]:
#addition of two arryas


#total addition
import numpy  as np

n1=np.array([10,20,30])
n2=np.array([30,40,50])

np.sum ([n1,n2])

180

In [3]:
#addition of column using 0 axis:

np.sum([n1,n2],axis=0)

array([40, 60, 80])

In [6]:
#addition of row using 1 axis:


np.sum([n1,n2],axis=1)

array([ 60, 120])

In [7]:
#saving and loding of array:


#saving:
np.save('my_array',n1)

In [9]:
#loading
n3=np.load ('my_array.npy')
n3

array([10, 20, 30])

In [12]:
#basic addition of arrays:

#adding 1
n1=np.array([12,34,56,78])
n1=n1+1
n1

#multiplication

print n1

array([13, 35, 57, 79])

In [16]:
#multiplication

print (n1)

n1=n1*2
n1

[ 26  70 114 158]


array([ 52, 140, 228, 316])

In [18]:
#substraction

print (n1)

n1=n1-200
n1

[ 50 138 226 314]


array([-150,  -62,   26,  114])

In [19]:
#division

print (n1)

n1=n1/200
n1

[-150  -62   26  114]


array([-0.75, -0.31,  0.13,  0.57])

In [20]:
#numpy match function:
#mean
n1=np.array([23,43,54,3,5,65])


np.mean(n1)

32.166666666666664

In [21]:
#std
n1=np.array([23,43,54,3,5,65])


np.std(n1)

23.610849671755194

In [22]:
#median
n1=np.array([23,43,54,3,5,65])


np.median(n1)

33.0

In [27]:
#numpy insertion & difference:
n1=np.array([12,23,43,54,56])
n2=np.array([23,32,43,34,13])

#intersect
np.intersect1d(n1,n2)

#setdifference
np.setdiff1d(n1,n2)

#setdifference
np.setdiff1d(n2,n1)

array([13, 32, 34])

In [29]:
#joining of arrays:

#vsatak()
#hstack()
#column_stack()

#vstack:

n1=np.array([12,23,43,54,56])
n2=np.array([23,32,43,34,13])

np.vstack((n1,n2))



array([[12, 23, 43, 54, 56],
       [23, 32, 43, 34, 13]])

In [30]:
#hsatck:

n1=np.array([12,23,43,54,56])
n2=np.array([23,32,43,34,13])

np.hstack((n1,n2))


array([12, 23, 43, 54, 56, 23, 32, 43, 34, 13])

In [32]:
#column_stack
n1=np.array([12,23,43,54,56])
n2=np.array([13,32,43,34,13])

np.column_stack((n1,n2))


array([[12, 13],
       [23, 32],
       [43, 43],
       [54, 34],
       [56, 13]])

In [37]:
#initializing array:

#arange
n1=np.arange(10,50)

n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [43]:
#3rd value is diffrence:
n1=np.arange(10,110,10)

n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [46]:
#pandas Series object:

import pandas as pd

n1=np.arange(10,50)

n1

0     1
1     2
2    34
3     5
4     6
dtype: int64

In [50]:
#finding  the  tpyr of array:
n1=pd.Series([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

type (n1)


pandas.core.series.Series

In [56]:
#pandas indexing:
n1=pd.Series([ 10,  20,  30,  40,  50],index=["A","B","C","D","E"])

n1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [60]:
#using dictionary:
n1=pd.Series({"a":12,"b":43,"c":23})
n1

a    12
b    43
c    23
dtype: int64

In [68]:
#extracting a single element:
n1=pd.Series([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

a=n1[0]
b=n1[3]

print (a ,"and",b)


10 and 40


In [69]:
#4 elements
n1[:4]

0    10
1    20
2    30
3    40
dtype: int64

In [70]:
#above 4:
n1[4:]

4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [71]:
#negtive:
n1[-4:]

6     70
7     80
8     90
9    100
dtype: int64

In [74]:
s1=pd.Series([12,23,34,45,65,76])
s2=pd.Series([23,32,12,32,43,54])

#addition:
s1+s2


0     35
1     55
2     46
3     77
4    108
5    130
dtype: int64

In [78]:
import pandas as pd
pd.DataFrame({"Names":["DATTA","RAHUL","ADITYA"],"AGE":[54,34,87]})



Names  AGE
0   DATTA   54
1   RAHUL   34
2  ADITYA   87